export const // eslint-disable-line one-var
    SET_AUTHENTICATED = 'SET_AUTHENTICATED',
    SET_LAWS = 'SET_LAWS',
    SET_NEWS = 'SET_NEWS',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_PARTNERS = 'SET_PARTNERS',
    SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS';
