export const // eslint-disable-line one-var
    SET_AUTHENTICATED = 'SET_AUTHENTICATED',
    SET_ABOUT = 'SET_ABOUT',
    SET_NEWS = 'SET_NEWS',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_PARTNERS = 'SET_PARTNERS',
    SET_RVV_PLANS = 'SET_RVV_PLANS',
    SET_SEO = 'SET_SEO',
    SET_RVV = 'SET_RVV',
    SET_LAW = 'SET_LAW';
