export const // eslint-disable-line one-var
    SET_AUTHENTICATED = 'SET_AUTHENTICATED',
    SET_NEWS = 'SET_NEWS',
    SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS',
    SET_CATEGORIES = 'SET_CATEGORIES';
