export const // eslint-disable-line one-var
    SET_LANG_MAP = 'SET_LANG_MAP',
    SET_LANG_ROUTE = 'SET_LANG_ROUTE',
    SET_LANG = 'SET_LANG',
    SET_MEDIA_INFO = 'SET_MEDIA_INFO',
    SET_NEWS = 'SET_NEWS',
    SET_ABOUT = 'SET_ABOUT',
    SET_LAW = 'SET_LAW',
    SET_NEWS_CATEGORIES = 'SET_NEWS_CATEGORIES',
    SET_MENU_OPEN = 'SET_MENU_OPEN',
    SET_SEO = 'SET_SEO',
    SET_ACTIVE_CATEGORY_INDEX = 'SET_ACTIVE_CATEGORY_INDEX',
    SET_PARTNERS = 'SET_PARTNERS';
